set(GLEW_FOUND TRUE)
if(NOT TARGET GLEW::glew)
    if(TARGET libglew_static)
        add_library(GLEW::glew ALIAS libglew_static)
    elseif(TARGET libglew_shared)
        add_library(GLEW::glew ALIAS libglew_shared)
    endif()
endif()
